apiVersion: apps/v1
kind: Deployment
metadata:
  name: results
spec:
  replicas: 1
  selector:
    matchLabels:
      app: results
  template:
    metadata:
      labels:
        app: results
    spec:
      containers:
        - name: results
          image: nobletk/results:v1
          imagePullPolicy: Always
          env:
            - name: REDIS_ADDR
              value: "redis:6379"
          ports:
            - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: results
spec:
  selector:
    app: results
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
